### ISSUE TITLE
Run this repo

### ISSUE THREAD

**Issue by hendisantika** [gauravbrills/jasperreportswithspringboot#1]
Nice repo.

But, Can you give me guide how to run this repo?

Thanks

**Comment by gauravbrills** [comment]
Most should be pretty straightforward being a spring boot app . The only thing is I didnt quite use a embedded database so might be referencing my mysql database for this . You can change the report to point to your database and then I guess things must work well ./

**Comment by gauravbrills** [comment]
added guide
